#!/usr/bin/env python


# import necessary packages

from email.mime.multipart import MIMEMultipart
from email.mime.text import MIMEText
import smtplib, requests, datetime, os

def detect_public_ip():
    try:
        # Use a get request for api.duckduckgo.com
        raw = requests.get('https://api.duckduckgo.com/?q=ip&format=json')

        # Optional:
        ##import requests
        ##myPublic_IP = requests.get("http://wtfismyip.com/text").text.strip()
        #### dato = urllib.request.urlopen("http://checkip.dyndns.org").read()
        ##print("\n[+] My Public IP: "+ myPublic_IP+"\n")
        #

        # load the request as json, look for Answer.
        # split on spaces, find the 5th index ( as it starts at 0 ), which is the IP address
        answer = raw.json()["Answer"].split()[4]
    # if there are any connection issues, error out
    except Exception as e:
        return 'Error: {0}'.format(e)
    # otherwise, return answer
    else:
        return answer






message = detect_public_ip()
verIP = " "

# Read IP of myIP.txt
if os.path.exists("myIP.txt") and os.path.isfile("myIP.txt") :
    arch = open("myIP.txt", 'r')
    verIP = arch.read()
    arch.close()

if not ( str(verIP) == str(message) and os.path.exists("myIP.txt") and os.path.isfile("myIP.txt")) :

    # create message object instance
    msg = MIMEMultipart()

    # setup the parameters of the message
    password = "MyPassword"
    msg['From'] = "myuser@gmail.com"
    msg['To'] = "friend@gmail.com"
    msg['Subject'] = "Nueva IP en casa  "+ str((datetime.datetime.today()).date())

    # add in the message body
    msg.attach(MIMEText(message, 'plain'))

    # create server
    server = smtplib.SMTP('smtp.gmail.com: 587')

    server.starttls()

    # Login Credentials for sending the mail
    server.login(msg['From'], password)

    # send the message via the server.
    server.sendmail(msg['From'], msg['To'], msg.as_string())

    server.quit()

    # save IP in myIP.txt
    arch = open("myIP.txt", 'w')
    arch.write(message)
    arch.close()

    print "successfully sent email to %s:" % (msg['To'])


